from collections.abc import Callable
from typing import Any

class Exit(Exception):
    def __init__(self, code: int = 0) -> None: ...

def echo(*args: Any, **kwargs: Any) -> None: ...
def Argument(*args: Any, **kwargs: Any) -> Any: ...

# ruff: noqa: N818,N802

class Typer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def command(
        self, *args: Any, **kwargs: Any
    ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
