"""Initial recipe schema

Revision ID: b4161f4c8a0a
Revises:
Create Date: 2025-10-19 21:25:09.676638

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4161f4c8a0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("servings", sa.String(length=100), nullable=True),
        sa.Column("prep_time", sa.Integer(), nullable=True),
        sa.Column("cook_time", sa.Integer(), nullable=True),
        sa.Column("total_time", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "ingredients_json", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "instructions_json", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("changelog", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("tips", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("cuisine", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_name"), "recipes", ["name"], unique=False)
    op.create_index(op.f("ix_recipes_slug"), "recipes", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipes_slug"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_name"), table_name="recipes")
    op.drop_table("recipes")
    # ### end Alembic commands ###
